name: Documentation

on:
  push:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: docs
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install hatch
        uses: pypa/hatch@install
      - name: Build the docs
        run: hatch run docs:build
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
          force_orphan: true
